global: {}

ibm-platform-navigator-instance:
  ibmplatformnavigator:
    name: integration-navigator
    spec:
      license:
        accept: true
        license: L-YBXJ-ADJNSM
      mqDashboard: true
      version: 2023.4.1
      replicas: 2   